class Config(object):

    BLUR_KERNEL_SIZE = 9
    SOBEL_KERNEL_SIZE = -1
    BINARY_THRESHOLD_1ST = 120
    BINARY_THRESHOLD_2ND = 255
    ERODE_ITER = 14
    DILATE_ITER = 14
    GSE_KERNEL_SIZE = 25
    AREA_THRESHOLD = 5000

    #Contrast ratio config
    CONTRAST_MIN_RATE = 0.85
    CONTRAST_MAX_RATE = 0.04
